### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by zeaugusto** [kminami/apib2swagger#34]
Hi, when I convert apib to swagger the "version" field in the swagger file is not filled, giving problem to import into API Gateways.

Is this right?

Thank you

**Comment by kminami** [comment]
Are you talking about Amazon API Gateway?
If your apib includes appropriate "version" field, I can implement to convert it to swagger.
Maybe, filling it with "1.0.0" statically is NOT help?

**Comment by zeaugusto** [comment]
Yes, I'm talking about AWS API Gateway.
I can't fill it statically because the conversion runs in a DevOps Pipeline, so I would need to handle the .json file in a script or something like that.

Maybe, you could set a default value to version instead of empty value. 
There is no reference of version in the api blueprint documentation.

Thanks
José

**Comment by IonGyth** [comment]
Hey,

I was also thinking about something similar. I looked at the blueprint api repo and my understanding is: https://github.com/apiaryio/api-blueprint/issues/258#issuecomment-134655760
>  Note when it comes to separate blueprint versions you can use GitHub to help with this since your blueprint is just a versioned file in a repo.

So it looks like they just expect us to update the docs alongside the code instead of specifying versions.

My thoughts were we could do something similar as with 'HOST: http://example.com' but instead use something like 'VERSION: 1.0.0' that way we know that what we're doing is not specifically part of the spec and don't start designing our own additions.

Another solution could be to instead of / in addition add a command line argument if editing the documentation is not an option.

As it stands 'version' shows as required for the swagger/openapi spec so we should provide a value (https://swagger.io/specification/#infoObject)

I'm open to other suggestions and I hope this would solve any issues.

**Comment by kminami** [comment]
Support 'VERSION' metadata at v1.5.0.
Thank you both!
